{{- range $name, $parameters := .Values.providerClasses }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ $.Values.vaultAddress }}
    roleName: {{ $parameters.roleName }}
    objects: |
      {{- range $parameters.objects }}
      - objectName: {{ .objectName }}
        secretPath: {{ .secretPath }}
        secretKey: {{ .secretKey }}
      {{- end }}
{{- end }}
