vaultAddress: http://vault-openbao.vault.svc.cluster.internal:8200
providerClasses: {}
  # foo:
  #   roleName: "example-role"
  #   objects:
  #     - objectName: "result"
  #       secretPath: "secret/data/path/in/vault"
  #       secretKey: "key-in-vault"
