replicaCount: 1

image:
  repository: cloudflared/cloudflared
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Tunnel config
tunnel: example-tunnel
ingress:
  - hostname: mytunnel.example.com
    service: myservice.mynamespace.svc.cluster.local
