apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel }}
    credentials-file: /etc/cloudflared/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      {{- with .Values.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - service: http_status:404
